### ISSUE TITLE
Lag due to EntityItemTickEvent

### ISSUE THREAD

**Issue by LemADEC** [Vazkii/AutoRegLib#14]
As of 1.3-20, CPU lag is observed in WorldTickEvent:
- LagGoggle consistently report 0.5 to 0.6 ms per tick
![image](https://user-images.githubusercontent.com/4776032/44629417-6b269000-a94f-11e8-9be6-2302cd1d2216.png)

- WarmRoast reports typically 0.5% usage
![image](https://user-images.githubusercontent.com/4776032/44629509-c442f380-a950-11e8-8b65-b9c51f99c3ae.png)

From a quick code review, every tick, for every entity item, a new Event is created and fired, even when no mod is registered on said event:
https://github.com/Vazkii/AutoRegLib/blob/master/src/main/java/vazkii/arl/util/ItemTickHandler.java#L22

**Comment by Vazkii** [comment]
How many entities were in the world at the time of this happening? You'd need a lot of entities for this to be relevant at all I reckon?

**Comment by LemADEC** [comment]
Using VisualVM memory profiler, at least 35% of BlockPos allocations were referring to that custom event. There was ~1900 item entities loaded at the time.
