### ISSUE TITLE
(1.12.2) poof! crashes

### ISSUE THREAD

**Issue by Migmag789** [Vazkii/AutoRegLib#15]
I was playing on a server, I made a (Open Blocks) xp shower and I crashed :( A installed mod named VanillaFix said this is AutoRegLib that is the cause of the crash. Can you help me please ? :D 

https://paste.dimdev.org/yihuyafuzi.mccrash

Forge version : 14.23.4.2757
AutoRegLib version : AutoRegLib-1.3-19
OpenBlocks version : OpenBlocks-1.12.2-1.7.6

Good luck ! :D

**Comment by Vazkii** [comment]
Update autoreglib.

**Comment by Migmag789** [comment]
Ok thank you ^^
