### ISSUE TITLE
Can we use this for Electrical Age?

### ISSUE THREAD

**Issue by Baughn** [Vazkii/AutoRegLib#37]
I'm confused by the license(s). Not being a lawyer, I can't evaluate whether or not it's okay for us to do... much of anything, honestly; I'm only familiar with how GPL/BSD/etc. apply to this situation. So, I'm going to explain what we'd like to do and let you decide instead.

In short:
  - Electrical Age v2 (https://github.com/eln2/eln2) is MIT-licensed.
  - We'd like to link to AutoRegLib using a Maven & CurseForge dependency. It will not be shadowed into the jar. I'm pretty sure your license isn't MIT-compatible, so that was never an option.
  - It's not a dealbreaker if we can't, I think, but we'd also like the option to git-subtree the mod into our repository if we end up needing to modify it, to simplify development while waiting for PR response.
  - Obviously, we'd also like to link AutoRegLib into the same running Java binary as part of running a Minecraft client. As far as I can tell, it also doesn't allow that. (But see "Confused by licenses.")

**Comment by Vazkii** [comment]
Sure knock yourselves out
