### ISSUE TITLE
Issue with version 1.6-43

### ISSUE THREAD

**Issue by ZAKsPop** [Vazkii/AutoRegLib#47]
When I upgrade to 1.6-43 from 1.6-42 I get this message when I try to load any save.

Errors in currently selected datapacks prevented world from loading. You can either try to load only with vanilla datapack ("safe mode") or go back to the title screen and fix it manually.

I removed all my datapacks and all my resource packs but that didn't work. The only way to play is revert back to 1.6-42 and older Quark. Yes, I have many other mods. Yes I have Optifine.  I tried with forge 32.0.75, 32.0.77, 32.0,90 and 32.0.93

**Comment by FirEmerald** [comment]
Can confirm this issue persists even if autoreglib and quark are the only installed mods.

**Comment by ChrisTheBear** [comment]
I’m getting this problem too and I can’t play because of it

**Comment by FirEmerald** [comment]
> I’m getting this problem too and I can’t play because of it

you can downgrade to 1.6-42 assuming that you aren't running forge 32.0.90 or later

**Comment by Vazkii** [comment]
You can sort this by updating to the latest forge, no downgrading of versions required.
