### ISSUE TITLE
quark r1.2-75 crashes dedicated Forge 1.11.2 build 2223 on startup

### ISSUE THREAD

**Issue by kreezxil** [Vazkii/AutoRegLib#6]
Notes:
     I have the latest autoreglib installed 1.1-4

crash report:
https://gist.github.com/fcf07426c9fa702a5d2bb655e26a5d08

fml server latest:
https://gist.github.com/707e16ad3fbc316b0b59cf66edfe8812

**Comment by Vazkii** [comment]
https://github.com/Vazkii/Quark/commit/280b680b151cd9cdb1ce7ff1b4d19e5378b79b58
