### ISSUE TITLE
Version for 1.12 marked as 1.11

### ISSUE THREAD

**Issue by xbony2** [Vazkii/AutoRegLib#7]
The latest version of AutoRegLib on CurseForge, [1.2-5](https://minecraft.curseforge.com/projects/autoreglib/files/2434212), is marked for use in Minecraft version 1.11.2. However, this update is the port to Minecraft 1.12, as described in the changelog. This is very silly and you should feel bad about yourself.

**Comment by Vazkii** [comment]
:|

**Comment by xbony2** [comment]
❤️
